# Загрузка Pandas и очистка данных

In [1]:
import pandas as pd
import numpy as np
import re
import math
from datetime import datetime

In [6]:
df = pd.read_csv('main_task.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Restaurant_id      40000 non-null  object
 1   City               40000 non-null  object
 2   Cuisine Style      30717 non-null  object
 3   Ranking            40000 non-null  float64
 4   Rating             40000 non-null  float64
 5   Price Range        26114 non-null  object
 6   Number of Reviews  37457 non-null  float64
 7   Reviews            40000 non-null  object
 8   URL_TA             40000 non-null  object
 9   ID_TA              40000 non-null  object
dtypes: float64(3), object(7)
memory usage: 3.1+ MB

In [2]:

# Ваш код по очистке данных и генерации новых признаков
# При необходимости добавьте ячейки

# 1. Где количестов отзывов не указано пишем 0
df['Number of Reviews'].fillna(0, inplace=True)
#print(df['Price Range'].unique())

cuisine = set()
# \w	[0-9a-z_] любая цифра, буква или знак подчеркивания
# + - одно или болле вхождений
# * - ноль или болле вхождений
# \s [ \t\v\r\n\f] пробельный символ
df['Cuisine Style'].fillna('European', inplace=True)
df['Cuisine Style'] = df['Cuisine Style'].str.findall('\w+\s*\w*\s*\w*')

cuisines = set()  # создаём пустое множество для хранения уникальных значений кухонь
for styles in df['Cuisine Style']:
    for item in styles:
        cuisines.add(item)


def find_item(cell):
    if item in cell:
        return 1
    return 0


for item in cuisines:
    df[item] = df['Cuisine Style'].apply(find_item)

# Добавляем признак - количество кухонь
df['CuisineCount'] = df['Cuisine Style'].apply(lambda x: len(x))

sum = df.CuisineCount.sum()
length = len(df.CuisineCount)
sum/length

#pat = re.compile('\w+\s*\w*\s*\w*')
#cuisine_styles = df['Cuisine Style'].dropna().apply(lambda x: ['default'] if pd.isnull(x) else pat.findall(x))
# cuisine_styles.explode().value_counts(ascending=False)
#
# для One-Hot Encoding в pandas есть готовая функция - get_dummies. Особенно радует параметр dummy_na
#df = pd.get_dummies(df, columns=['City', 'Price Range'], dummy_na=True)
df.corr()

,Ranking,Rating,Number of Reviews,Central American,Romanian,Greek,Seafood,Barbecue,Steakhouse,Fujian,...,Kosher,Healthy,Filipino,Spanish,Venezuelan,Afghani,Arabic,Mexican,Ethiopian,CuisineCount
Ranking,1.000000,-0.368371,-0.222072,-0.018318,0.001863,-0.068879,-0.074082,-0.039053,-0.042967,-0.003196,...,0.004984,-0.021510,-0.007166,-0.016425,-0.006948,0.003787,-0.008968,-0.001241,-0.006911,-0.320111
Rating,-0.368371,1.000000,0.026924,0.000929,0.004896,0.044228,0.012870,0.003314,0.000941,0.005363,...,-0.004501,0.058532,0.008819,-0.026251,0.001513,0.004233,0.006661,-0.021004,0.013041,0.120134
Number of Reviews,-0.222072,0.026924,1.000000,0.044804,-0.005056,0.005137,0.127686,0.053792,0.073270,-0.001754,...,0.014020,-0.007661,-0.001890,0.052395,-0.002264,-0.003223,-0.005665,0.005467,0.000045,0.405577
Central American,-0.018318,0.000929,0.044804,1.000000,-0.000920,-0.007205,-0.011506,0.015208,0.003868,-0.000411,...,-0.002017,-0.007302,-0.001008,-0.002439,0.052711,-0.001365,-0.002079,0.347267,-0.001887,0.079427
Romanian,0.001863,0.004896,-0.005056,-0.000920,1.000000,-0.001958,-0.003127,-0.001876,-0.001906,-0.000112,...,-0.000548,-0.001984,-0.000274,0.001863,-0.000500,-0.000371,-0.000565,-0.001677,-0.000513,0.005021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Afghani,0.003787,0.004233,-0.003223,-0.001365,-0.000371,-0.002905,-0.004638,0.006333,-0.002828,-0.000166,...,-0.000813,0.005688,-0.000406,-0.006433,-0.000742,1.000000,0.029043,-0.002488,-0.000761,0.024813
Arabic,-0.008968,0.006661,-0.005665,-0.002079,-0.000565,0.001321,-0.007065,0.007740,-0.004307,-0.000253,...,-0.001238,-0.004483,-0.000619,-0.007052,-0.001130,0.029043,1.000000,-0.003790,-0.001158,0.040562
Mexican,-0.001241,-0.021004,0.005467,0.347267,-0.001677,-0.007270,-0.019720,0.003720,0.003260,-0.000750,...,-0.003676,0.011775,-0.001837,0.007356,0.026809,-0.002488,-0.003790,1.000000,-0.003439,0.044955
Ethiopian,-0.006911,0.013041,0.000045,-0.001887,-0.000513,-0.004014,-0.006410,-0.003846,-0.003908,-0.000229,...,-0.001124,-0.004068,-0.000562,-0.008891,-0.001026,-0.000761,-0.001158,-0.003439,1.000000,0.013522
CuisineCount,-0.320111,0.120134,0.405577,0.079427,0.005021,0.035728,0.186529,0.112919,0.078027,0.003412,...,0.036591,0.129918,0.013919,0.088607,0.030934,0.024813,0.040562,0.044955,0.013522,1.000000

In [3]:

def reviews_date(rew, count):
    try:
        date = re.findall(r'\d\d?/\d\d?/\d+', rew)
        
        lenDate = len(date)
        if count == 3:
            return lenDate
        if lenDate == 0:
            return np.nan
        if count == 1:
            #return pd.to_datetime(date[0])
            return math.log(pd.to_datetime(date[0]).timestamp())
        elif lenDate == 2:
            #return pd.to_datetime(date[1])
            return math.log(pd.to_datetime(date[1]).timestamp())
        else:
            return np.nan
    except Exception:
        return np.nan
    
    
def len_reviews(item):
    try:
        len(re.findall(r'[a-zA-Z]', item))
    except Exception:
        return np.nan

    
def preproc_data(df_input):
    '''includes several functions to pre-process the predictor data.'''
    
    df_output = df_input.copy()
    
    # ################### 1. Предобработка ############################################################## 
    # убираем не нужные для модели признаки
    df_output.drop(['Restaurant_id','ID_TA',], axis = 1, inplace=True)
    
    
    # ################### 2. NAN ############################################################## 
    # Далее заполняем пропуски, вы можете попробовать заполнением средним или средним по городу и тд...
    df_output['Number of Reviews'].fillna(0, inplace=True)
    df_output['Cuisine Style'].fillna('European', inplace=True)
    
    citys = df_output.City.value_counts()
    df_output.City = df_output.City.apply(lambda x: x if citys[x]>100 else np.nan)
    # ################### 3. Encoding ############################################################## 
    # для One-Hot Encoding в pandas есть готовая функция - get_dummies. Особенно радует параметр dummy_na
    df_output = pd.get_dummies(df_output, columns=['City', 'Price Range'], dummy_na=True)

    # ################### 4. Feature Engineering ####################################################
    cuisine = set()
    
    df_output['Cuisine Style'] = df_output['Cuisine Style'].str.findall('\w+\s*\w*\s*\w*')

    cuisines = set()  # создаём пустое множество для хранения уникальных значений кухонь
    for cuisinesList in df_output['Cuisine Style']:
        for cuisine in cuisinesList:
            cuisines.add(cuisine)


    def find_item(cell):
        if item in cell:
            return 1
        return 0


    for item in cuisines:
        df_output[item] = df_output['Cuisine Style'].apply(find_item)

    # Добавляем признак - количество кухонь
    df_output['Cuisine Count'] = df_output['Cuisine Style'].apply(lambda x: len(x))
    
    df_output['Reviews_first'] = df_output['Reviews'].apply(lambda x: reviews_date(x, 1))
    df_output['Reviews_second'] = df_output['Reviews'].apply(lambda x: reviews_date(x, 2))
    df_output['Reviews_Count'] = df_output['Reviews'].apply(lambda x: reviews_date(x, 3))
    
    df_output['Reviews_first'].fillna(df_output['Reviews_first'].mean(), inplace=True)
    df_output['Reviews_second'].fillna(df_output['Reviews_second'].mean(), inplace=True)
    df_output['Reviews_Count'].fillna(0, inplace=True)
    
    # ################### 5. Clean #################################################### 
    # убираем признаки которые еще не успели обработать, 
    # модель на признаках с dtypes "object" обучаться не будет, просто выберим их и удалим
    object_columns = [s for s in df_output.columns if df_output[s].dtypes == 'object']
    df_output.drop(object_columns, axis = 1, inplace=True)
    return df_output

# Разбиваем датафрейм на части, необходимые для обучения и тестирования модели

In [4]:
# всегда фиксируйте RANDOM_SEED, чтобы ваши эксперименты были воспроизводимы!
RANDOM_SEED = 42
# зафиксируем версию пакетов, чтобы эксперименты были воспроизводимы:
!pip freeze > requirements.txt

# Х - данные с информацией о ресторанах, у - целевая переменная (рейтинги ресторанов)
df_preproc = preproc_data(pd.read_csv('main_task.csv'))

X = df_preproc.drop(['Rating'], axis = 1)
y = df_preproc['Rating']

# Загружаем специальный инструмент для разбивки:
from sklearn.model_selection import train_test_split
# Наборы данных с меткой "train" будут использоваться для обучения модели, "test" - для тестирования.
# Для тестирования мы будем использовать 25% от исходного датасета.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=RANDOM_SEED)
df_preproc.corr()

,Ranking,Rating,Number of Reviews,City_Amsterdam,City_Athens,City_Barcelona,City_Berlin,City_Bratislava,City_Brussels,City_Budapest,...,Spanish,Venezuelan,Afghani,Arabic,Mexican,Ethiopian,Cuisine Count,Reviews_first,Reviews_second,Reviews_Count
Ranking,1.000000,-0.368371,-0.222072,-0.094372,-0.095177,0.017390,-0.026367,-0.075669,-0.095232,-0.095534,...,-0.016425,-0.006948,0.003787,-0.008968,-0.001241,-0.006911,-0.320111,-0.180685,-1.784008e-01,-1.397488e-01
Rating,-0.368371,1.000000,0.026924,0.034535,0.044792,-0.012890,0.046967,-0.002988,-0.020753,0.020950,...,-0.026251,0.001513,0.004233,0.006661,-0.021004,0.013041,0.120134,0.090483,8.794726e-02,2.052373e-02
Number of Reviews,-0.222072,0.026924,1.000000,0.013348,-0.010741,0.006194,-0.046995,-0.021603,-0.019411,0.014622,...,0.052395,-0.002264,-0.003223,-0.005665,0.005467,0.000045,0.405577,0.195188,2.184668e-01,2.139044e-01
City_Amsterdam,-0.094372,0.034535,0.013348,1.000000,-0.021098,-0.045249,-0.039864,-0.014546,-0.027562,-0.024108,...,-0.025309,-0.005285,-0.003919,0.011274,0.010146,0.004083,0.063350,0.043373,4.613918e-02,6.195754e-02
City_Athens,-0.095177,0.044792,-0.010741,-0.021098,1.000000,-0.034208,-0.030137,-0.010997,-0.020837,-0.018225,...,-0.032271,-0.003996,-0.002963,0.006759,0.001943,0.008325,-0.002122,-0.003709,-1.456061e-03,1.510346e-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Ethiopian,-0.006911,0.013041,0.000045,0.004083,0.008325,-0.005722,0.005940,-0.002823,0.004263,-0.004679,...,-0.008891,-0.001026,-0.000761,-0.001158,-0.003439,1.000000,0.013522,0.009878,8.142327e-03,1.571936e-02
Cuisine Count,-0.320111,0.120134,0.405577,0.063350,-0.002122,0.004088,-0.043825,-0.017745,-0.011327,0.049984,...,0.088607,0.030934,0.024813,0.040562,0.044955,0.013522,1.000000,0.318386,3.402307e-01,3.725304e-01
Reviews_first,-0.180685,0.090483,0.195188,0.043373,-0.003709,-0.010627,-0.032599,-0.006750,0.001230,0.011517,...,0.003590,0.008317,0.005970,0.012942,0.024449,0.009878,0.318386,1.000000,5.726735e-01,1.573197e-01
Reviews_second,-0.178401,0.087947,0.218467,0.046139,-0.001456,-0.005063,-0.038035,-0.003466,-0.002406,0.011182,...,0.007247,0.008886,0.006023,0.008900,0.023348,0.008142,0.340231,0.572674,1.000000e+00,-4.833240e-12
Reviews_Count,-0.139749,0.020524,0.213904,0.061958,0.015103,-0.026926,-0.031013,0.004085,0.005082,0.034891,...,0.010498,-0.001576,0.003705,0.000285,0.030834,0.015719,0.372530,0.157320,-4.833240e-12,1.000000e+00

# Создаём, обучаем и тестируем модель

In [5]:
# Импортируем необходимые библиотеки:
# инструмент для создания и обучения модели
from sklearn.ensemble import RandomForestRegressor
from sklearn import metrics  # инструменты для оценки точности модели
# Создаём модель
regr = RandomForestRegressor(
    n_estimators=100, verbose=1, n_jobs=-1, random_state=RANDOM_SEED)

# Обучаем модель на тестовом наборе данных
regr.fit(X_train, y_train)

# Используем обученную модель для предсказания рейтинга ресторанов в тестовой выборке.
# Предсказанные значения записываем в переменную y_pred
y_pred = regr.predict(X_test)
# Сравниваем предсказанные значения (y_pred) с реальными (y_test), и смотрим насколько они в среднем отличаются
# Метрика называется Mean Absolute Error (MAE) и показывает среднее отклонение предсказанных значений от фактических.
print('MAE:', metrics.mean_absolute_error(y_test, y_pred))

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    5.1s
[Parallel(n_jobs=-1)]: Done 100 out of 100 | elapsed:   13.1s finished
[Parallel(n_jobs=8)]: Using backend ThreadingBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done  34 tasks      | elapsed:    0.0s

MAE: 0.207898

[Parallel(n_jobs=8)]: Done 100 out of 100 | elapsed:    0.0s finished